apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-pv-deployment
  labels:
    run: hello-nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello-nginx
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: nginx-pv-container
          image: nginx-demo:test
          ports:
            - containerPort: 80
              name: "http-server"
          volumeMounts:
            - mountPath: "/var/www/html"
              name: task-pv-storage
      restartPolicy: Always
