apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    run: hello-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30303
  selector:
    run: hello-nginx
  type: NodePort
status:
  loadBalancer: {}
